//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCServis.CaferServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_DERSPROG", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TBL_DERSPROG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BASLIKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALTYAZIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESIMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BASLIK {
            get {
                return this.BASLIKField;
            }
            set {
                if ((object.ReferenceEquals(this.BASLIKField, value) != true)) {
                    this.BASLIKField = value;
                    this.RaisePropertyChanged("BASLIK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ALTYAZI {
            get {
                return this.ALTYAZIField;
            }
            set {
                if ((object.ReferenceEquals(this.ALTYAZIField, value) != true)) {
                    this.ALTYAZIField = value;
                    this.RaisePropertyChanged("ALTYAZI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AY {
            get {
                return this.AYField;
            }
            set {
                if ((object.ReferenceEquals(this.AYField, value) != true)) {
                    this.AYField = value;
                    this.RaisePropertyChanged("AY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string GUN {
            get {
                return this.GUNField;
            }
            set {
                if ((object.ReferenceEquals(this.GUNField, value) != true)) {
                    this.GUNField = value;
                    this.RaisePropertyChanged("GUN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string YIL {
            get {
                return this.YILField;
            }
            set {
                if ((object.ReferenceEquals(this.YILField, value) != true)) {
                    this.YILField = value;
                    this.RaisePropertyChanged("YIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RESIM {
            get {
                return this.RESIMField;
            }
            set {
                if ((object.ReferenceEquals(this.RESIMField, value) != true)) {
                    this.RESIMField = value;
                    this.RaisePropertyChanged("RESIM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CaferServis.CaferSoap")]
    public interface CaferSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MVCServis.CaferServis.HelloWorldResponse HelloWorld(MVCServis.CaferServis.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCServis.CaferServis.HelloWorldResponse> HelloWorldAsync(MVCServis.CaferServis.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name tumDerslerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tumDersler", ReplyAction="*")]
        MVCServis.CaferServis.tumDerslerResponse tumDersler(MVCServis.CaferServis.tumDerslerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tumDersler", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCServis.CaferServis.tumDerslerResponse> tumDerslerAsync(MVCServis.CaferServis.tumDerslerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MVCServis.CaferServis.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MVCServis.CaferServis.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCServis.CaferServis.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MVCServis.CaferServis.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class tumDerslerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="tumDersler", Namespace="http://tempuri.org/", Order=0)]
        public MVCServis.CaferServis.tumDerslerRequestBody Body;
        
        public tumDerslerRequest() {
        }
        
        public tumDerslerRequest(MVCServis.CaferServis.tumDerslerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class tumDerslerRequestBody {
        
        public tumDerslerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class tumDerslerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="tumDerslerResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCServis.CaferServis.tumDerslerResponseBody Body;
        
        public tumDerslerResponse() {
        }
        
        public tumDerslerResponse(MVCServis.CaferServis.tumDerslerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class tumDerslerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<MVCServis.CaferServis.TBL_DERSPROG> tumDerslerResult;
        
        public tumDerslerResponseBody() {
        }
        
        public tumDerslerResponseBody(System.Collections.Generic.List<MVCServis.CaferServis.TBL_DERSPROG> tumDerslerResult) {
            this.tumDerslerResult = tumDerslerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CaferSoapChannel : MVCServis.CaferServis.CaferSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaferSoapClient : System.ServiceModel.ClientBase<MVCServis.CaferServis.CaferSoap>, MVCServis.CaferServis.CaferSoap {
        
        public CaferSoapClient() {
        }
        
        public CaferSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaferSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaferSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaferSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCServis.CaferServis.HelloWorldResponse MVCServis.CaferServis.CaferSoap.HelloWorld(MVCServis.CaferServis.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MVCServis.CaferServis.HelloWorldRequest inValue = new MVCServis.CaferServis.HelloWorldRequest();
            inValue.Body = new MVCServis.CaferServis.HelloWorldRequestBody();
            MVCServis.CaferServis.HelloWorldResponse retVal = ((MVCServis.CaferServis.CaferSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCServis.CaferServis.HelloWorldResponse> MVCServis.CaferServis.CaferSoap.HelloWorldAsync(MVCServis.CaferServis.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCServis.CaferServis.HelloWorldResponse> HelloWorldAsync() {
            MVCServis.CaferServis.HelloWorldRequest inValue = new MVCServis.CaferServis.HelloWorldRequest();
            inValue.Body = new MVCServis.CaferServis.HelloWorldRequestBody();
            return ((MVCServis.CaferServis.CaferSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCServis.CaferServis.tumDerslerResponse MVCServis.CaferServis.CaferSoap.tumDersler(MVCServis.CaferServis.tumDerslerRequest request) {
            return base.Channel.tumDersler(request);
        }
        
        public System.Collections.Generic.List<MVCServis.CaferServis.TBL_DERSPROG> tumDersler() {
            MVCServis.CaferServis.tumDerslerRequest inValue = new MVCServis.CaferServis.tumDerslerRequest();
            inValue.Body = new MVCServis.CaferServis.tumDerslerRequestBody();
            MVCServis.CaferServis.tumDerslerResponse retVal = ((MVCServis.CaferServis.CaferSoap)(this)).tumDersler(inValue);
            return retVal.Body.tumDerslerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCServis.CaferServis.tumDerslerResponse> MVCServis.CaferServis.CaferSoap.tumDerslerAsync(MVCServis.CaferServis.tumDerslerRequest request) {
            return base.Channel.tumDerslerAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCServis.CaferServis.tumDerslerResponse> tumDerslerAsync() {
            MVCServis.CaferServis.tumDerslerRequest inValue = new MVCServis.CaferServis.tumDerslerRequest();
            inValue.Body = new MVCServis.CaferServis.tumDerslerRequestBody();
            return ((MVCServis.CaferServis.CaferSoap)(this)).tumDerslerAsync(inValue);
        }
    }
}
